SELECT ROWNUM, name, score
FROM EX_SCORE
WHERE ROWNUM <= 5
ORDER BY score DESC;

-- 중첩쿼리(FROM절 - 인라인뷰) - 괄호안을 먼저 실행해야 함
SELECT ROWNUM, name, score
FROM (SELECT * FROM EX_SCORE
        ORDER BY score DESC)
WHERE ROWNUM <= 5;

-- JOB_INFO 테이블 생성
CREATE TABLE JOB_INFO (
    JOB_ID      VARCHAR(10),
    MIN_SALARY  NUMBER,
    MAX_SALARY  NUMBER
);

INSERT INTO JOB_INFO VALUES ('AD_PRES', 20080, 40000);
INSERT INTO JOB_INFO VALUES ('AD_VP', 15000, 30000);
INSERT INTO JOB_INFO VALUES ('AD_ASST', 3000, 6000);
INSERT INTO JOB_INFO VALUES ('FI_MGR', 9200, 16000);
INSERT INTO JOB_INFO VALUES ('FI_ACCOUNT', 4200, 9000);
INSERT INTO JOB_INFO VALUES ('AC_MGR', 8200, 16000);
INSERT INTO JOB_INFO VALUES ('AC_ACCOUNT', 4200, 9000);

COMMIT;

UPDATE JOB_INFO SET MIN_SALARY = 8200
WHERE JOB_ID = 'FI_MGR';

SELECT * FROM JOB_INFO;

-- 집계 함수(COUNT(), AVG(), SUM(), MAX(), MIN())
SELECT  COUNT(*) 전체직업수,
        ROUND(AVG(MIN_SALARY), -1) 최저급여평균,
        AVG(MAX_SALARY) 최고급여평균
FROM JOB_INFO;

-- 최저 급여가 5000달러 이상인 직업의 이름을 검색하시오
SELECT JOB_ID, MIN_SALARY "min_sal"
FROM JOB_INFO
WHERE MIN_SALARY >= 5000;
-- WHERE min_sal >= 5000; -- 실행순서가 SELECT 전이므로 별칭 사용 불가

-- 최저 급여가 5000달러 이상인 직업의 이름을 검색한 뷰를 만드시오
-- CREATE VIEW 뷰이름 AS 구문
CREATE VIEW V_JOB_INFO
AS SELECT *
   FROM JOB_INFO
   WHERE MIN_SALARY >= 5000;

SELECT * FROM V_JOB_INFO;

-- 뷰 삭제
DROP VIEW V_JOB_INFO;

-- 최고 급여와 최저 급여의 차가 8000달러 이상인 직업 아이디의 수를 검색하시오
SELECT COUNT(JOB_ID) 직업수
FROM V_JOB_INFO
WHERE MAX_SALARY - MIN_SALARY >= 8000;

-- 최고 급여와 최저 급여의 차가 8000달러 이상인 직업 아이디를 검색하시오
SELECT JOB_ID 직업명
FROM V_JOB_INFO
WHERE MAX_SALARY - MIN_SALARY >= 8000;

-- 직업 아이디의 이름이 AD로 시작하는 자료를 검색하시오
SELECT  JOB_ID 직업명,
        MIN_SALARY 최저연봉,
        MAX_SALARY 최고연봉
FROM V_JOB_INFO
WHERE JOB_ID LIKE '%AD%';




